### ISSUE TITLE
убрать повторения

### ISSUE THREAD

**Issue by baltun** [kapxapot/associations#2]
запретить в процессе одной игры использовать одни и те же слова как компьютеру, так и человеку

**Comment by kapxapot** [comment]
В процессе...

**Comment by kapxapot** [comment]
ИИ уже не может использовать повторные слова. Игрока пока может.

**Comment by baltun** [comment]
иии =)

**Comment by kapxapot** [comment]
ИИ = комп, не важно. ;)

Для игроков планируется пока сделать 2 режима игры:

1. Обучающий (с повторами)
2. Соревновательный (без повторов)

**Comment by baltun** [comment]
повторы и их запрет - имеется ввиду внутри одной игры?
если да, то не вижу смысла в том, чтобы разрешать их использовать в целях обучения, т.к. можно использовать изученные ассоциации в новой игре

в целях обучения можно добавить кнопку Сдаюсь, и записывать слова, на которых сдался человек, и давать ему на него одну или несколько ассоциаций, а также периодически начинать с них игру

**Comment by kapxapot** [comment]
Да, в рамках одной игры все.
Ну у некоторых игроков есть методы, которые основаны на повторах. :)))

А вот кнопка "Сдаюсь" или "Закончить игру" -- отличная идея. Это нужно прям щас. :)

Можно еще "Подсказки" сделать.
