### ISSUE TITLE
сохранять каждое использование ассоциации отдельно и с временем использования

### ISSUE THREAD

**Issue by baltun** [kapxapot/associations#5]
для того, чтобы понимать, как часто встречается ассоциация, нужно сохранять каждую ассоциацию не один раз, а столько, сколько раз она использовалась, плюс сохранять время её использования. Тогда можно будет считать её вес не просто на основе количества её использования, а еще и делить на количество времени, прошедшее от текущего момента, когда её использовали. Т.е. каждая ассоциация добавляет не 1, а какую-то дробную часть, уменьшающуюся со временем (по аналогии с нейронными связями)

**Comment by kapxapot** [comment]
Сохраняется уже.

Схема таблицы ходов игры:

CREATE TABLE IF NOT EXISTS `turns` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `game_id` int NOT NULL,
  `user_id` int,
  `word_id` int NOT NULL,
  **`association_id` int,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,**
  `finished_at` timestamp DEFAULT NULL,
  `prev_turn_id` int,
  PRIMARY KEY (`id`),
)
