### ISSUE TITLE
оценка людьми слов

### ISSUE THREAD

**Issue by baltun** [kapxapot/associations#6]
добавить возможность игрокам, увидевшим слово от компьютера "забраковать" его.
слова с несколькими браками далее каким-то образом автоматически или полуавтоматически убирать из участия в игре, а при попытке повторного добавления ругаться на игрока =)

**Comment by kapxapot** [comment]
Такое планируется с самого начала идеи игры. Обязательно. :)

Но мы пойдем еще дальше! Мы кривые слова и ассоциации не будем удалять, а будем их помечать для игнорирования при игре с другими игроками. Но с автором этого косяка все равно будем его использовать. Бугагагага!

**Comment by baltun** [comment]
тогда можно показывать ему, сколько человек это слово забраковали и дать возможность его не использовать

**Comment by baltun** [comment]
>>Но мы пойдем еще дальше! 
а мы?

**Comment by kapxapot** [comment]
Детали пока не ясны, есть пока только идея.
Для начала надо будет сделать возможность игрокам делать отметки типа "плохое слово", "плохая ассоциация".

**Comment by kapxapot** [comment]
Добавлены следующие возможности по фидбэку по слову:

- Не нравится
- Опечатка
- Дублирует другое слово
- Не для детей
