### ISSUE TITLE
оценка людьми ассоциации

### ISSUE THREAD

**Issue by baltun** [kapxapot/associations#7]
добавить возможность игрокам при предоставлении компьютером ассоциации пометить эту ассоциацию как "странная", или как-то еще, для дальнейшего управления ассоциациями

**Comment by kapxapot** [comment]
Тоже планируется наряду с #6.

**Comment by kapxapot** [comment]
Сделано.

Можно указывать, что ассоциация:

- Не нравится
- Не для детей
