### ISSUE TITLE
части речи

### ISSUE THREAD

**Issue by baltun** [kapxapot/associations#9]
дать возможность игрокам причислять слова к частям речи
[Части речи](https://best-language.ru/nekotorye-chasti-rechi)
существительное - предмет, явление
прилагательное - описывает свойство
глагол - описывает действие
частицы - предлоги, междометия, союзы
имена - названия единичных объектов

**Comment by kapxapot** [comment]
Это уже получается какой-то семантический словарь, а не просто игра.
Думаю, пока это преждевременно. Да и самой игре это совсем никак не поможет.

**Comment by kapxapot** [comment]
Реализовано в dev. Для проверки части речи используется Яндекс.Словарь.
